data_path: /home/euro/Projects/open-source/pyovpn/test
debug: true
general:
  default_names:
    COMMON_NAME: OpenVPN cert
    ORGANIZATIONAL_UNIT_NAME: Some unit
    ORGANIZATION_NAME: Some company
  log_length: 100
  openvpn_binary: /usr/bin/openvpn
static_path: /home/euro/Projects/open-source/pyovpn/pyovpn/static
users:
  root:
    is_admin: true
    is_anonymouse: false
    password: 4813494d137e1631bba301d5acab6e7bb7aa74ce1185d456565ef51d737677b2
    username: root
  test:
    is_admin: false
    is_anonymouse: false
    password: 9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08
    username: test
    vpns: []
vpns:
  test:
    enabled: false
web:
  jsonrpc: /api/jsonrpc
  port: 8085
  websock: /api/ws
