data_path: /home/sauron/Projects/os/pyovpn/test
debug: true
general:
  default_names:
    COMMON_NAME: OpenVPN cert
    ORGANIZATIONAL_UNIT_NAME: Some unit
    ORGANIZATION_NAME: Some company
  log_length: 100
  openvpn_binary: /usr/bin/openvpn
users:
  root:
    is_admin: true
    is_anonymouse: false
    password: 4813494d137e1631bba301d5acab6e7bb7aa74ce1185d456565ef51d737677b2
    username: root
vpns:
  test:
    enabled: false
web:
  jsonrpc: /api/jsonrpc
  port: 8085
  websock: /api/ws
