data_path: /home/euro/Projects/open-source/pyovpn/test
general:
  default_names:
    COMMON_NAME: OpenVPN cert
    ORGANIZATIONAL_UNIT_NAME: Some unit
    ORGANIZATION_NAME: Some company
  openvpn_binary: /usr/bin/openvpn
  log_length: 100
users:
  root:
    is_admin: true
    is_anonymouse: false
    password: heslo
  test:
    is_admin: false
    is_anonymouse: false
    password: test

vpns: {}
web:
  jsonrpc: /api/jsonrpc
  port: 8085
  websock: /api/ws
